### ISSUE TITLE
Add sub-menu pages to the "About" section

### ISSUE THREAD

**Issue by gmolinario** [GFDRR/geonode-afghanistan#10]
We will need to expand on the "about" section to contain information specific to the Afghanistan project. 

We will request the following support: 

1.  Add a "Project Information" sub-menu under the "About" section. 
2. Group the "people", "groups" and "group categories" under a sub-heading titled "Users" 
3. develop and host the page/s for "Project Information" using a template that has the look and feel of the AF geonode. 
4. Support in adding text, images and videos to the page created. # #

**Comment by gmolinario** [comment]
A draft of  the new webpage is here: https://docs.google.com/document/d/1QZlC__Gh4s6QF24wCdtUl70WdjfOZodWzIHBIOClyUc/edit?usp=sharing

**Comment by cgiovando** [comment]
@afabiani @simboss - do you need anything else from @gmolinario to proceed with this?

**Comment by gmolinario** [comment]
Hi @simboss  and @afabiani and @cgiovando , can you let me know what is the timeline for this task? Do you expect that we can start this week? 

Thanks again for your help,

Giuseppe

**Comment by afabiani** [comment]
@gmolinario @cgiovando first draft available https://disasterrisk.af/

**Comment by gmolinario** [comment]
> @gmolinario @cgiovando first draft available https://disasterrisk.af/

Thanks so much @afabiani  - looks good. Could you make the headings bold, and center the video? I'll provide you asap the finalized main text of the sections so you can copy and paste. Thanks!

**Comment by afabiani** [comment]
@gmolinario done

**Comment by gmolinario** [comment]
Hi @afabiani, 

I finalized the text. Can you please copy and paste it into the page? 

A couple other things: 

1) in copying and pasting it looks like all the " ' " have become " . " , can you please check that they are pasted correctly. 
2) can you remove the last heading "Videos" and instead create it as it's own sub-menu under the "about" main menu? The title of the sub menu is "Tutorial Videos" . I will have to give you the finalized text and links here as well as we finish the videos. 

Thank you!

**Comment by afabiani** [comment]
@gmolinario done, can you please check?

**Comment by gmolinario** [comment]
hi @afabiani thanks for that - I just noticed I had missed something. Can you please replace the text under heading 3? I've highlighted in yellow in the google doc. Thanks!

**Comment by afabiani** [comment]
@gmolinario done.

**Comment by simboss** [comment]
@gmolinario @cgiovando you can close this if/once you are happy with it.

**Comment by gmolinario** [comment]
hi @afabiani could you set the hyperlinks in the new project information page to open in a new tab? 

Thank you

**Comment by afabiani** [comment]
@gmolinario done.
