### ISSUE TITLE
Giving an entire group the ability to download layers

### ISSUE THREAD

**Issue by gmolinario** [GFDRR/geonode-afghanistan#3]
I made an account for a consultant for the project (kcoates) and added her to a new group i made, called "consultants". I gave the group permission to view all layers, but cannot find the permission that allows the group also to see the metadata and download the layers. I know admins can do this, but I want to give this permission to that group, and not give her any admin access (will be useful also for ongoing trainings!)

**Comment by gmolinario** [comment]
hi @cgiovando  - sorry I lost track, was this closed because it's part of #8 ?

**Comment by afabiani** [comment]
@gmolinario yes. The management command, runnable from the shell only, is already in place. 
We would need to create a GNIP to add to GeoNode a GUI allowing an admin to run the command from the web as well.

**Comment by gmolinario** [comment]
hi @afabiani  - I think that's worth doing. Perhaps with lower priority than the other things we still have open. What do you think @cgiovando ?

**Comment by cgiovando** [comment]
This is basically what was proposed in #8, so this issue is dependent on that - I asked GS to provide an estimate here http://gfdrr.geo-solutions.it/support/tickets/19306

**Comment by gmolinario** [comment]
> This is basically what was proposed in #8, so this issue is dependent on that - I asked GS to provide an estimate here http://gfdrr.geo-solutions.it/support/tickets/19306

apologies @cgiovando but i can't seem to login anymore to that platform? Tried with my saved credentials :(

**Comment by cgiovando** [comment]
@simboss @afabiani to deploy on disasterrisk.af, then send a patch for local instance

**Comment by cgiovando** [comment]
@simboss @afabiani can you confirm this has been deployed at least in the online version?

**Comment by afabiani** [comment]
@cgiovando yes, I confirm.
