### ISSUE TITLE
Some layers do not download

### ISSUE THREAD

**Issue by gmolinario** [GFDRR/geonode-afghanistan#4]
Speaking of layer downloads, i noticed unfortunately that even as an admin, I'm not able to download one of the layers the consultant is interested in: Earthquake Shaking - PGA in g, 2500y return period . When selecting the gtiff download, i get the following exception report in xml (attached).  Any ideas on how to get this to work?

**Comment by cgiovando** [comment]
Can you post a link to the layer and the returned XML error? Thanks!

**Comment by gmolinario** [comment]
> Can you post a link to the layer and the returned XML error? Thanks!

several do (potentially all -  I haven't done a thorough check). One that has the issue is: "Flood Hazard Exposure, 1000years RP - Total Damage (US$)"

the xml is:

<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/2.0 http://schemas.opengis.net/ows/2.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>
illegal bbox, minX: 58.3639774694 is greater than maxX: 24.7284008948 []
</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
