### ISSUE TITLE
Thumbnail view / zoom level 

### ISSUE THREAD

**Issue by gmolinario** [GFDRR/geonode-afghanistan#5]
before the last troubleshooting of issues the thumbnails of layers were set to a closer extent which actually showed the features. Now it's as if the thumbnails were reset to "maximum" extent of the layer, which means that in most cases, it looks like there is actually no thumbnail at all, as the features are lost among a mostly white thumbnail.

**Comment by afabiani** [comment]
Currently, for the raster layers the background is not rendered anymore on the thumbnails.

The side effect is that on the raster layers thumbs the image is barely visible.

Let's see if there's a quick way to refresh the thumbs along with the background.

**Comment by simboss** [comment]
@gmolinario with the upgrade there should have been an improvement also in how to thumbnails are computed, however I am afraid this is still not satisfactory for your scenario.

I will talk to @afabiani to see if we can come up with something to improve the behaviour of the thumbnails further.

**Comment by simboss** [comment]
So here is the situation.

You can manually edit the thumbnail to better fit the current styling, however the ratio of the new image is not always perfect.

We are putting together a fix for this (1D of work at most) which we are going to install on the afghanistan instance and test there on one of the raster layers for you to evaluate.

**Comment by simboss** [comment]
Dear Giuseppe,
we implemented the fix and demonstrated it to @cgiovando.

We are going to deploy this week, or beginning of next week the latest.

**Comment by simboss** [comment]
@gmolinario the fix has been deployed.

Now you can decide to manually adjust the thumbnail on a single layer as I am showing in the video below for [this](https://disasterrisk.af/layers/geonode:wp2_historic_1978) layer. Notice that I clean the cache to make sure I see the changes right away.

![emits](https://user-images.githubusercontent.com/693880/66927822-c6728080-f030-11e9-8891-dc50d2d99f03.gif)
