### ISSUE TITLE
All 1291 layers are visible in the public version

### ISSUE THREAD

**Issue by gmolinario** [GFDRR/geonode-afghanistan#6]
Before the last troubleshooting of issues, only about 100 layers were visible to the 'non-authenticated" public. Now unfortunately all 1291 issues are visible to everyone all the time. Can this issue be resolved and only the layers that were flagged to be public be shown to the public? This was the case a few months ago.

**Comment by afabiani** [comment]
Check if we can retrieve the old list of the public layers only.

Once we have the list the easiest thing to do would be to:

- Remove the public access in batch to all the layers
- Envisage if it is possible to create a small script reading the list of public layers and setting the permissions to those ones only

**Comment by simboss** [comment]
@gmolinario can you come up with a list of what should be public and what should not be so that we can quickly fix this?

**Comment by gmolinario** [comment]
@simboss @afabiani  @cgiovando the list is in the excel attached.
[geonode_data_list_finalsummary_rev_GM.xlsx](https://github.com/GFDRR/geonode-afghanistan/files/3678765/geonode_data_list_finalsummary_rev_GM.xlsx)
 I filtered all the layers in the tabs, and then added all the public ones to the first tab. However, they are only 50~ as opposed to 90~ on the past GeoNode....so we lost some information somewhere. I'm not sure this is important, but it would be nice to know these types of things are backed up... can this info be retrieved somewhere from a backup?

**Comment by gioscarda** [comment]
@gmolinaro we will update layers permissions based on the attached excel, I will notify you when done.
Currently is not possible to retrieve the modification history for those layers.

**Comment by simboss** [comment]
@gmolinario @cgiovando we are updating the permissions as per the provided spreadsheet.
There might be some glitches for an hour or so.

I will update you once we are done.

**Comment by gioscarda** [comment]
@gmolinario @cgiovando the updating process has finished. Now anonymous users can view only the layers provided in the spreadsheet.

**Comment by afabiani** [comment]
@gmolinario @cgiovando just one more thing:

In order to allow an "anonymous" user to access the "Risk Analaysis & Cost Benefit Tool" we need to make publicly accessible the two layers:

* https://disasterrisk.af/layers/geonode:risk_analysis_data
* https://disasterrisk.af/layers/geonode:risk_analysis

Containing the risk analysis data sets. Those layers are not listed among the ones into the spreadsheet.

Do we need to hide them also?

If "yes", should we envisage to hide the top bar menu links to the Risk Tools to anonymous users also?

**Comment by gmolinario** [comment]
Hi @afabiani  - sorry for the delay - yes please make public any layers that are needed for any of the tools/maps to work correctly for anonymous users. Thank you.

**Comment by gmolinario** [comment]
hi @afabiani can we close this one?

**Comment by simboss** [comment]
Done
