### ISSUE TITLE
Make a GNIP on GeoNode for batch permissions

### ISSUE THREAD

**Issue by afabiani** [GFDRR/geonode-afghanistan#8]
Currently, there is a management command allowing a sys admin to modify the permissions to the resources in batch mode.

It would be good to have a gui on the GeoNode admin dashboard allowing also a super user to run the command from the web interface.

**Comment by cgiovando** [comment]
Hi @gmolinario - unless this is an issue currently affecting the AF instance, I would remove it from the [first milestone](https://github.com/GFDRR/geonode-afghanistan/milestone/1) - this can be done independently directly in the main GeoNode repo

**Comment by simboss** [comment]
This is going through the GNIP process for GeoNode.

The initial version is [here](https://github.com/GeoNode/geonode/issues/5274), I have asked to clarify better how this would look like from the administratore perspective. We can then ask you to review.

**Comment by simboss** [comment]
HI @cgiovando and @gmolinario, please, check the GNIP reported above as we updated it with some schreenshots.

Alessio will move forward with the development shortly, so feedback is good to have now.
