### ISSUE TITLE
Upgrade the disasterrisk instance and risk modules to GeoNode 2.10.x

### ISSUE THREAD

**Issue by afabiani** [GFDRR/geonode-afghanistan#9]
Currently, the "disasterrisk" instance, along with the disaster management risk tools, are based on GeoNode 2.8.2.

We would like to move those apps to GeoNode 2.10.x

- [x] Make an estimation
- [x] Port the apps to GeoNode 2.10.x

**Comment by simboss** [comment]
This is done, pending the switch of the instances.

**Comment by simboss** [comment]
Instances switched.

Closing.
